### ISSUE TITLE
[Bug]: Differing mudra starters break the timeline

### ISSUE THREAD

**Issue by Nicolas-GE** [Zeffuro/ZDs#2]
### What are you trying to do?

using Ten→Chi→Jin Suiton, followed by Jin→Ten→Chi Doton

### What is the expected behavior?

When the first cooldown for "Ten" is over, the cooldown for "Jin" appears at 20 seconds

### What actually happened?

Once the cooldown of Ten is over, there is no second mudra cooldown

### Suggested solution

instead of having each mudra as unique cooldowns, having one icon to define the mudra's cooldown would increase clarity, either just the "Ten" icon, or the "Ninjutsu" icon
or maybe another option entirely?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and ZDs.

**Comment by Nicolas-GE** [comment]
this issue also applies to all abilities that share cooldowns and have more than 1 charge, such as Bard's Rain of Death/Bloodletter, and many blue mage actions

**Comment by Zeffuro** [comment]
This is mostly fixed in the next version for most jobs. For Blue Mage I am far behind the curve (I'm still lvl 70 and missing several spells), it'd help me if I had a list of spells that share cooldown and which spell is considered "primary" (under the hood I set the actionID to the same to the charges stay tracked on that).

**Comment by Nicolas-GE** [comment]
my mistake on the blue mage side of things, while a handful of the 124 spells do share cooldowns, they do not have more than one charge, only the ravana spell does, which is unique!

**Comment by Zeffuro** [comment]
Oh all good then, that saves me from having to go through Blie Mage for now :) Thank you for checking!

**Comment by Nicolas-GE** [comment]
my bad, small correction, Winged Reprobation, while not having any charged on the spell, gives a buff that counts up to 4, where it will incur its spell-speed dependant cooldown, only then and not before

also, i just found that canceling a cast on a spell with a large cooldown will still display it on the bar, though i should make that a seperate issue i think
