### ISSUE TITLE
[Suggestion]: Blacklist all spells by default

### ISSUE THREAD

**Issue by Nicolas-GE** [Zeffuro/ZDs#4]
### What's your suggestion?

my understanding is that this plugin is meant to track oGCDs exclusively, if a spell is slow enough to be under the limit for the minimum setting, such as when afflicted with slow or casting Pictomancer motifs, they will start appearing on the timeline

i don't know how the spells+weaponskills / abilities are sorted out in the back end, but i think this should be looked at

**Comment by Zeffuro** [comment]
You can set the filter to whitelist instead if that's easier for you, I don't think we want to start with a full blacklist. It reverses the behaviour and makes it able to only let through what you want. It's for both oGCD and GCD.
You can alternatively just change the threshold:

![Advanced_Combat_Tracker_2024-08-26_04-00-46](https://github.com/user-attachments/assets/2b0cc84a-8833-4fff-bf70-5d75bd4ba4c4)

**Comment by Zeffuro** [comment]
Did this make sense and can I close this or is there any functionality missing if I don't do this?
